// <auto-generated />
using BackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Año")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorreoEditorial")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DirecciorCorrespondencia")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaximoLibros")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreEditorial")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroPaginas")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("libro");
                });
#pragma warning restore 612, 618
        }
    }
}
